### ISSUE TITLE
About Synthetic Dataset

### ISSUE THREAD

**Issue by Iceeteeea** [miccunifi/analog-video-restoration#2]
Thanks for your work!
Could I get the access to your synthetic dataset?

**Comment by LorenzoAgnolucci** [comment]
Hi @Iceeteeea!

Thanks for your interest in our work!

The synthetic dataset is available in the [repo](https://github.com/miccunifi/TAPE) associated with the [follow-up](https://arxiv.org/abs/2310.14926) of this work.
