### ISSUE TITLE
There is no "requirements.txt" file

### ISSUE THREAD

**Issue by dberga** [miccunifi/analog-video-restoration#3]
As far as I could notice, these packages are needed

numpy
torch
torchvision
pytorch-lightning
einops

**Comment by LorenzoAgnolucci** [comment]
Hi @dberga!

Thanks for your interest in our work!

You are right, the requirements.txt file was missing as I forgot to upload it. Sorry for the silly mistake.

If you have any other questions or find another bug feel free to open a new issue.
